<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<?php echo $this->headTitle() ?>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>LeagueWatch</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url( array( 'controller'=>'profile' ), 'default', true ) ?>">Profile</a>
    </div>
</div>

<?php if(isset($_COOKIE['summoner'])) { ?>
	
<?php } ?>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>