<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<?php echo $this->headTitle() ?>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Leaguewatch</title>
  <?php echo $this->headLink()->appendStylesheet('/layouts/main.css') ?>
</head>
<body>
<div class="centered">
	
</div>

<div class="searchbox">
	<?php echo $this->layout()->content ?>
</div>
 
</body>
</html>